name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Vous pouvez ajuster selon la branche que vous souhaitez surveiller

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.Name }}
        password: ${{ secrets.Secret }}

    - name: Build Docker image
      run: |
        docker build -t yourdockerhubusername/yourimage:latest .

    - name: Push Docker image
      run: |
        docker push yourdockerhubusername/yourimage:latest
